networks:
  default:
    driver: bridge

services:
  fe:
    image: mapletool-fe
    build:
      context: frontend
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
